alter table ENTERPRISELABA_TICKET add constraint FK_ENTERPRISELABA_TICKET_ON_SHOW foreign key (SHOW_ID) references ENTERPRISELABA_SHOW(ID);
create index IDX_ENTERPRISELABA_TICKET_ON_SHOW on ENTERPRISELABA_TICKET (SHOW_ID);
