alter table ENTERPRISELABA_THEATRE add constraint FK_ENTERPRISELABA_THEATRE_ON_ADMIN foreign key (ADMIN_ID) references SEC_USER(ID);
create index IDX_ENTERPRISELABA_THEATRE_ON_ADMIN on ENTERPRISELABA_THEATRE (ADMIN_ID);
