alter table ENTERPRISELABA_SHOW add constraint FK_ENTERPRISELABA_SHOW_ON_FILM foreign key (FILM_ID) references ENTERPRISELABA_FILM(ID);
alter table ENTERPRISELABA_SHOW add constraint FK_ENTERPRISELABA_SHOW_ON_THEATRE foreign key (THEATRE_ID) references ENTERPRISELABA_THEATRE(ID);
alter table ENTERPRISELABA_SHOW add constraint FK_ENTERPRISELABA_SHOW_ON_AUDITORIUM foreign key (AUDITORIUM_ID) references ENTERPRISELABA_AUDITORIUM(ID);
create index IDX_ENTERPRISELABA_SHOW_ON_FILM on ENTERPRISELABA_SHOW (FILM_ID);
create index IDX_ENTERPRISELABA_SHOW_ON_THEATRE on ENTERPRISELABA_SHOW (THEATRE_ID);
create index IDX_ENTERPRISELABA_SHOW_ON_AUDITORIUM on ENTERPRISELABA_SHOW (AUDITORIUM_ID);
